### ISSUE TITLE
plugin could not compile

### ISSUE THREAD

**Issue by gabzony** [JustOptimize/return-ShowHiddenChannels#153]
Discord Stable 243588 (0168cc1)
Host 1.0.9021 x86 (39082)
Windows 10 64-Bit (10.0.19045)
BetterDiscord Core v.1.9.5

Receiving the following error on startup:

`TypeError: Cannot destructure property 'Sf' of 'WebpackModules.getModule(...)' as it is undefined.
    at plugin (betterdiscord://plugins/ShowHiddenChannels.plugin.js:180:17)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1576:10)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1577:3)
    at D.requireAddon (betterdiscord/renderer.js:5:33852)
    at D.loadAddon (betterdiscord/renderer.js:5:6322)
    at D.loadAddon (betterdiscord/renderer.js:5:31520)
    at D.loadAllAddons (betterdiscord/renderer.js:5:8814)
    at D.initialize (betterdiscord/renderer.js:5:3194)
    at D.initialize (betterdiscord/renderer.js:5:30719)
    at Object.startup (betterdiscord/renderer.js:5:385713)`

**Comment by JustOptimize** [comment]
Update the plugin, you're using an old version

**Comment by gabzony** [comment]
ah, my bad
