### ISSUE TITLE
ShowHiddenChannels could not be compiled

### ISSUE THREAD

**Issue by master3395** [JustOptimize/return-ShowHiddenChannels#156]
This error comes every time you restart discord.
It will not let you enable the plugin.

```
TypeError: Cannot destructure property 'Sf' of 'WebpackModules.getModule(...)' as it is undefined.
    at plugin (betterdiscord://plugins/ShowHiddenChannels.plugin.js:180:17)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1576:10)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1577:3)
    at D.requireAddon (betterdiscord/renderer.js:5:33852)
    at D.loadAddon (betterdiscord/renderer.js:5:6322)
    at D.loadAddon (betterdiscord/renderer.js:5:31520)
    at D.loadAllAddons (betterdiscord/renderer.js:5:8814)
    at D.initialize (betterdiscord/renderer.js:5:3194)
    at D.initialize (betterdiscord/renderer.js:5:30719)
    at Object.startup (betterdiscord/renderer.js:5:385713)
```

![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/4199669/d5326b30-044d-4d7d-9a46-730e2564b7b2)
![Skjermbilde 2023-11-09 192740](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/4199669/7a369411-a0a5-4659-a3d3-314a2c9d1ca9)

**Comment by Jury76** [comment]
Remove and Reinstall the plugin as per the [https://github.com/JustOptimize/return-ShowHiddenChannels#how-to-install](Installation Instructions).

**Comment by master3395** [comment]
> Remove and Reinstall the plugin as per #127
