### ISSUE TITLE
Zeres Plugin error

### ISSUE THREAD

**Issue by flukcekku** [JustOptimize/return-ShowHiddenChannels#187]
TypeError: Cannot read properties of undefined (reading 'prototype')
    at ./src/ui/colorpicker.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3845:56)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/types/color.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5147:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4792:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6125:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1712:60)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3585:80)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:656:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1567:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6215:65)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6322:3)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6325:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at betterdiscord/renderer.js:5:4392

**Comment by JustOptimize** [comment]
Tracking links:
https://github.com/rauenzi/BDPluginLibrary/issues/221
https://github.com/rauenzi/BDPluginLibrary/issues/219

**Comment by flukcekku** [comment]
> Tracking links:
> https://github.com/rauenzi/BDPluginLibrary/issues/221
> https://github.com/rauenzi/BDPluginLibrary/issues/219

It work on stable version or not?

**Comment by flukcekku** [comment]
Ok work on discord official stable version

**Comment by Lusiiky** [comment]
Work on Stable Discord.
Not on PTB.

Compilation error:
`TypeError: Cannot read properties of undefined (reading 'prototype')
    at ./src/ui/colorpicker.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3845:56)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/types/color.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5147:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4792:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6125:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1712:60)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3585:80)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:656:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1567:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6215:65)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6322:3)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6325:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)`

**Comment by JustOptimize** [comment]
> Work on Stable Discord. Not on PTB.
> 
> Compilation error:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'prototype')
>     at ./src/ui/colorpicker.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3845:56)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/ui/settings/types/color.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5147:70)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4792:70)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6125:67)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1712:60)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3585:80)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816:65)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:656:65)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at ./src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1567:67)
>     at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
>     at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6215:65)
>     at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6322:3)
>     at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6325:12)
>     at N.requireAddon (betterdiscord/renderer.js:5:28792)
>     at N.loadAddon (betterdiscord/renderer.js:5:6412)
>     at N.loadAddon (betterdiscord/renderer.js:5:26460)
>     at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
>     at N.initialize (betterdiscord/renderer.js:5:3284)
>     at N.initialize (betterdiscord/renderer.js:5:25573)
>     at Object.startup (betterdiscord/renderer.js:5:408848)
> ```

As I already linked in the tracking links message...

**Comment by Aezukla** [comment]
Not working on Stable for me.

TypeError: Cannot read properties of undefined (reading 'prototype')
    at ./src/ui/colorpicker.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3845:56)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/types/color.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5147:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4792:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6125:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1712:60)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3585:80)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:656:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1567:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6215:65)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6322:3)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6325:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)
    
    ```md
## Discord Info
stable 301269 (6e5b8c9) Host 1.0.9148 x64 (48468) Build Override: N/A Windows 11 64-bit (10.0.22631)

## BetterDiscord
stable 1.10.1

**Comment by parknich** [comment]
Im on stable as far as im aware and its happening to me now too

**Comment by Meksis** [comment]
Same here

**Comment by JustOptimize** [comment]
> Same here

Saying this doesn't really make a difference, I'm not the author of the library and me receving an email and a message each time someone has a problem with it (when we already know it stopped working) it's quite useless

**Comment by flukcekku** [comment]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/125664297/18e98c8b-8b66-45b8-8ef8-b990e23cf840)


Have update, Discord PTB and Official Stable still work again

**Comment by flukcekku** [comment]
> > Same here
> 
> Saying this doesn't really make a difference, I'm not the author of the library and me receving an email and a message each time someone has a problem with it (when we already know it stopped working) it's quite useless

I'm sorry for that

**Comment by JustOptimize** [comment]
> I'm sorry for that

Don't worry, you did the right thing
